apiVersion: v1
kind: Pod
metadata:
  name: node-selector
  labels:
    purpose: "ebs-static-demo"
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a # kubectl get nodes --show-labels
  containers:
  - name: nginx
    image: nginx
   