apiVersion: v1
kind: Pod
metadata:
  name: node-selector-noexecute
  labels:
    purpose: "node-selector"
spec:
  nodeSelector:
    kubernetes.io/hostname: multinode-demo-m02 # kubectl get nodes --show-labels
  containers:
  - name: nginx
    image: nginx
  
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "cpu"
    effect: "NoExecute"


# kubectl taint nodes multinode-demo-m02 hardware=cpu:NoExecute