apiVersion: v1
kind: Pod
metadata:
  name: affinity
  labels:
    purpose: "affinity-demo"
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: hardware
            operator: In
            values:
            - cpu
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "cpu"
    effect: "NoExecute"